language: node_js

services:
  - xvfb

node_js:
  - 12.16.1

os:
  - linux
  - osx

osx_image: xcode11.3

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt update
      sudo apt install -y rpm snapd
      sudo snap install snapcraft --classic
    fi

script:
  - npm run lint
  - npm run test
  - npm run test:e2e
  - npm run build

notifications:
  email: false
